# Generated by Django 2.2.5 on 2019-12-02 23:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('AuthorID', models.IntegerField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(max_length=45)),
                ('last_name', models.CharField(max_length=45)),
                ('gender', models.CharField(max_length=45)),
                ('Date_of_Birth', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('isbn', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=45)),
                ('publish_date', models.DateField()),
                ('price', models.FloatField()),
                ('author', models.ManyToManyField(to='pages.Author')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('CategoryCode', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('CategoryDescription', models.CharField(max_length=45, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContactDetail',
            fields=[
                ('ContactID', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Judgement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, null=True)),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('Name', models.CharField(max_length=45, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='SupplierRep',
            fields=[
                ('sid', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=45)),
                ('last_name', models.CharField(max_length=45)),
                ('cell_number', models.CharField(max_length=13)),
                ('work_number', models.CharField(max_length=13)),
                ('email', models.CharField(max_length=45)),
            ],
            options={
                'unique_together': {('first_name', 'last_name')},
            },
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('number', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('ContactID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.ContactDetail')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('ItemNumber', models.AutoField(primary_key=True, serialize=False)),
                ('Item_Price', models.FloatField()),
                ('item', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.Book')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('OrderID', models.AutoField(primary_key=True, serialize=False)),
                ('Order_Date', models.DateField(auto_now=True)),
                ('Order_Value', models.FloatField(default=0)),
                ('items', models.ManyToManyField(to='pages.OrderItem')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('email', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.ContactDetail')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('CustomerID', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=45)),
                ('last_name', models.CharField(max_length=45)),
                ('ContactID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.ContactDetail')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='categorized',
            field=models.ManyToManyField(to='pages.Category'),
        ),
        migrations.AddField(
            model_name='book',
            name='supplied',
            field=models.ForeignKey(default='Walmart', on_delete=django.db.models.deletion.CASCADE, to='pages.Supplier'),
        ),
        migrations.AddField(
            model_name='author',
            name='ContactID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.ContactDetail'),
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('addr', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.ContactDetail')),
            ],
        ),
    ]
