# Generated by Django 2.2.5 on 2019-12-02 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='judgement',
            name='sampleFiels',
            field=models.IntegerField(default=0, max_length=12),
        ),
    ]
