# Generated by Django 2.2.5 on 2019-12-02 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='review',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
