# Generated by Django 2.2.7 on 2019-11-30 00:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('AuthorID', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=45)),
                ('last_name', models.CharField(max_length=45)),
                ('gender', models.CharField(max_length=45)),
                ('Date_of_Birth', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('isbn', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=45)),
                ('publish_date', models.DateField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('CategoryCode', models.IntegerField(primary_key=True, serialize=False)),
                ('CategoryDescription', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='ContactDetail',
            fields=[
                ('ContactID', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
            ],
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.AddField(
            model_name='book',
            name='categorized',
            field=models.ManyToManyField(to='pages.Category'),
        ),
        migrations.AddField(
            model_name='author',
            name='ContactID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.ContactDetail'),
        ),
    ]
