# Generated by Django 2.2.5 on 2019-12-02 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_judgement_samplefiels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='judgement',
            name='sampleFiels',
            field=models.IntegerField(default=0),
        ),
    ]
