# Generated by Django 2.2.7 on 2019-11-30 01:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20191129_1805'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('CustomerID', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=45)),
                ('last_name', models.CharField(max_length=45)),
                ('ContactID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.ContactDetail')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('OrderID', models.AutoField(primary_key=True, serialize=False)),
                ('Order_Date', models.DateField()),
                ('Order_Value', models.IntegerField()),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.Customers')),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('Name', models.CharField(max_length=45, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AlterField(
            model_name='author',
            name='AuthorID',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='CategoryCode',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='CategoryDescription',
            field=models.CharField(max_length=45, unique=True),
        ),
        migrations.CreateModel(
            name='SupplierRep',
            fields=[
                ('sid', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=45)),
                ('last_name', models.CharField(max_length=45)),
                ('cell_number', models.CharField(max_length=13)),
                ('work_number', models.CharField(max_length=13)),
                ('email', models.CharField(max_length=45)),
            ],
            options={
                'unique_together': {('first_name', 'last_name')},
            },
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('number', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('ContactID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.ContactDetail')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItems',
            fields=[
                ('ItemNumber', models.IntegerField(primary_key=True, serialize=False)),
                ('Item_Price', models.IntegerField()),
                ('OrderID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.Order')),
                ('isbn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.Book')),
            ],
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('email', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('cid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pages.ContactDetail')),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('addr', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('cid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pages.ContactDetail')),
            ],
        ),
    ]
