# Generated by Django 2.2.7 on 2019-11-30 01:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20191129_1939'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Customers',
            new_name='Customer',
        ),
        migrations.RenameModel(
            old_name='OrderItems',
            new_name='OrderItem',
        ),
        migrations.AlterField(
            model_name='address',
            name='cid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.ContactDetail'),
        ),
        migrations.AlterField(
            model_name='email',
            name='cid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.ContactDetail'),
        ),
    ]
