# Generated by Django 2.2.5 on 2019-12-03 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20191202_1759'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Judgement',
            new_name='Review',
        ),
    ]
