# Generated by Django 2.2.5 on 2019-12-01 03:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pages', '0005_book_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='OrderID',
        ),
        migrations.AddField(
            model_name='customer',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(to='pages.OrderItem'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='ItemNumber',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='Item_Price',
            field=models.DecimalField(decimal_places=1, max_digits=2),
        ),
    ]
