# Generated by Django 2.2.5 on 2019-12-03 00:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_auto_20191202_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='belongs',
            field=models.ForeignKey(default=122, on_delete=django.db.models.deletion.CASCADE, to='pages.Book'),
        ),
    ]
