# Generated by Django 2.2.5 on 2019-12-03 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_review_belongs'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='judgements',
            field=models.ManyToManyField(to='pages.Review'),
        ),
    ]
