# Generated by Django 2.2.5 on 2019-12-02 01:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_auto_20191130_2308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cid',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='user',
        ),
        migrations.AlterField(
            model_name='order',
            name='Order_Date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='item',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.Book'),
        ),
    ]
