# Generated by Django 2.2.5 on 2019-12-02 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_auto_20191201_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='Item_Price',
            field=models.DecimalField(decimal_places=2, max_digits=2),
        ),
    ]
