# Generated by Django 2.2.5 on 2019-12-02 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_auto_20191201_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='Item_Price',
            field=models.FloatField(),
        ),
    ]
