# Generated by Django 2.2.5 on 2019-12-03 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_contactdetail_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactdetail',
            name='addr',
            field=models.ManyToManyField(to='pages.Address'),
        ),
        migrations.AddField(
            model_name='contactdetail',
            name='c_email',
            field=models.ManyToManyField(to='pages.Email'),
        ),
    ]
