# Generated by Django 2.2.5 on 2019-12-02 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_auto_20191201_1940'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='supplied',
            field=models.ForeignKey(default=' ', on_delete=django.db.models.deletion.CASCADE, to='pages.Supplier'),
        ),
        migrations.AlterField(
            model_name='order',
            name='Order_Value',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='book',
            name='review',
            field=models.ManyToManyField(to='pages.Review'),
        ),
    ]
