# Generated by Django 2.2.5 on 2019-12-02 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_auto_20191202_0025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='supplied',
            field=models.ForeignKey(default='Walmart', on_delete=django.db.models.deletion.CASCADE, to='pages.Supplier'),
        ),
    ]
