# Generated by Django 2.2.5 on 2019-12-03 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_supplierrep_works_for'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplierrep',
            name='works_for',
        ),
    ]
