# Generated by Django 2.2.5 on 2019-12-03 04:46

from django.db import migrations, models
import django.db.models.deletion as dd


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_remove_supplierrep_works_for'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierrep',
            name='works_for',
            field=models.ForeignKey(default='Walmart', on_delete=dd.CASCADE,
                                    to='pages.Supplier'),
        ),
    ]
