# Generated by Django 2.2.5 on 2019-12-03 05:44

from django.db import migrations, models
import django.db.models.deletion as dd


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_supplierrep_works_for'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplierrep',
            name='works_for',
        ),
        migrations.AddField(
            model_name='supplier',
            name='rep',
            field=models.OneToOneField(null=True,
                                       on_delete=dd.CASCADE,
                                       to='pages.SupplierRep'),
        ),
    ]
