# Generated by Django 2.2.5 on 2019-12-03 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0015_auto_20191202_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='judgements',
            field=models.ManyToManyField(null=True, to='pages.Review'),
        ),
    ]
